import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Download, FileText } from "lucide-react";
import Container from "@/components/site/Container";
import CTASection from "@/components/site/CTASection";
import PageHero from "@/components/site/PageHero";
import SectionHeader from "@/components/site/SectionHeader";
import { resumeVariants, siteConfig } from "@/content/portfolio";

export const metadata: Metadata = {
  title: "Resume",
  description:
    "Two portfolio-ready resume variants — Senior AI Product Manager and AI Product Leader — generated from ResumeCustomizer, a source-grounded AI resume system Daniel Nash built.",
};

const resumeProfileJsonLd = {
  "@context": "https://schema.org",
  "@type": "ProfilePage",
  "@id": "https://www.danielnash.co/resume#profilepage",
  url: "https://www.danielnash.co/resume",
  name: "Daniel Nash Resume",
  description:
    "Resume page for Daniel Nash, a Senior AI Product Manager and AI product leader, with two portfolio-ready resume variants generated by ResumeCustomizer.",
  mainEntity: {
    "@id": "https://www.danielnash.co/#person",
  },
  relatedLink: [
    "https://www.danielnash.co/products/ai-career-operating-system",
    "https://www.danielnash.co/resume/generate",
    "https://www.danielnash.co/contact",
  ],
};

// Capabilities of the ResumeCustomizer system, surfaced so a hiring manager
// reads the resume system itself as AI product evidence.
const resumeSystemCapabilities = [
  "Role evaluation and fit scoring",
  "Template / positioning-lane selection",
  "Source-backed bullet selection",
  "Claim-to-evidence mapping",
  "Bridge strategy for adjacent-fit roles",
  "Multi-agent review: recruiter screen, ATS/readability, hiring-manager lens, source auditor, career positioning, bridge strategist",
  "Canonical final-resume.json generation",
  "Final PDF/HTML rendering with page-balance checks",
  "Guardrails against unsupported claims, fake metrics, and overpersonalization",
];

const productSignals = [
  "Agentic workflow design",
  "Source-grounded AI generation",
  "Multi-agent review and eval loops",
  "Human-in-the-loop judgment",
  "Product strategy and positioning systems",
  "Canonical rendering pipeline",
  "Quality guardrails and claim safety",
];

export default function ResumePage(): JSX.Element {
  return (
    <Container className="space-y-12 pb-20 pt-8 md:space-y-16 md:pb-28">
      <script
        type="application/ld+json"
        suppressHydrationWarning
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(resumeProfileJsonLd),
        }}
      />

      <PageHero
        eyebrow="Resume"
        title="Resume"
        description="Two portfolio-ready resume variants, generated from a source-grounded AI resume system I built to map real experience to role-specific evidence."
        metrics={[
          { label: "Variants", value: "2 portfolio-ready" },
          { label: "Built with", value: "ResumeCustomizer" },
          { label: "Delivery", value: "Open or download PDF" },
        ]}
      />

      {/* Primary downloads — kept obvious and high on the page. */}
      <section aria-labelledby="resume-downloads" className="space-y-6">
        <SectionHeader
          eyebrow="Pick the right read"
          title="Two resumes for evaluating Daniel"
          description="Each is a finalized resume rendered from canonical structured content — not a template preview and not tailored to any single company."
        />
        <h2 id="resume-downloads" className="sr-only">
          Resume downloads
        </h2>
        <div className="grid gap-6 md:grid-cols-2">
          {resumeVariants.map((variant) => (
            <article
              key={variant.id}
              id={variant.id}
              className="relative flex h-full scroll-mt-28 flex-col border-t border-[color:var(--color-slate)]/20 py-6 md:py-8"
            >
              {variant.legacyAnchors?.map((anchor) => (
                <span
                  key={anchor}
                  id={anchor}
                  aria-hidden="true"
                  className="block h-0 scroll-mt-28"
                />
              ))}

              <div className="space-y-3">
                <p className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.26em] text-[color:var(--color-teal)]/70">
                  <FileText aria-hidden="true" className="h-3.5 w-3.5" />
                  Resume variant
                </p>
                <h3 className="font-serif text-3xl font-medium leading-[1.05] tracking-[-0.035em] text-[color:var(--color-slate)]">
                  {variant.title}
                </h3>
                <p className="text-base font-medium leading-7 text-[color:var(--color-teal)]">
                  {variant.subtitle}
                </p>
              </div>

              <p className="mt-4 text-sm leading-6 text-[color:var(--color-slate)]/72">
                <span className="font-semibold text-[color:var(--color-slate)]">
                  Best for:{" "}
                </span>
                {variant.bestFor}
              </p>

              <ul className="mt-5 space-y-2 border-l-2 border-[color:var(--color-orange)] bg-[color:var(--color-background-soft)]/58 px-4 py-4 text-sm leading-6 text-[color:var(--color-slate)]/76">
                {variant.focusAreas.map((area) => (
                  <li key={area} className="flex gap-2">
                    <span
                      aria-hidden="true"
                      className="mt-2 h-1.5 w-1.5 flex-none rounded-full bg-[color:var(--color-orange)]"
                    />
                    <span>{area}</span>
                  </li>
                ))}
              </ul>

              <div className="mt-auto flex flex-wrap gap-3 pt-6">
                <a
                  href={`/resumes/${variant.filename}`}
                  download
                  className="inline-flex items-center gap-2 border border-[color:var(--color-teal)] bg-[color:var(--color-teal)] px-5 py-3 text-sm font-bold text-[color:var(--color-cream)] transition hover:bg-[color:var(--color-orange)]"
                >
                  <Download aria-hidden="true" className="h-4 w-4" />
                  {variant.ctaLabel}
                </a>
                <a
                  href={`/resumes/${variant.filename}`}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center border border-[color:var(--color-teal)]/22 px-5 py-3 text-sm font-bold text-[color:var(--color-teal)] transition hover:bg-white/35"
                >
                  Open PDF
                </a>
              </div>
            </article>
          ))}
        </div>
      </section>

      {/* The product behind the resumes — prominent, not buried. */}
      <section
        aria-labelledby="resume-system"
        className="relative overflow-hidden border-y border-white/8 bg-[color:var(--color-slate)] px-6 py-10 text-[color:var(--color-cream)] md:px-10 md:py-12"
      >
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,_rgba(219,191,150,0.18),_transparent_36%),radial-gradient(circle_at_bottom_right,_rgba(209,122,95,0.2),_transparent_44%)]"
        />
        <div className="relative space-y-8">
          <SectionHeader
            eyebrow="Built with ResumeCustomizer"
            title="The AI product behind these resumes"
            description="These resumes were generated with ResumeCustomizer, a product I built to solve my own job-search workflow: turning a large, source-audited career evidence base into role-specific, truthful, ATS-readable resumes."
            invert
          />

          <p className="max-w-3xl text-base leading-7 text-[color:var(--color-cream)]/78">
            ResumeCustomizer is an AI product system I built to make resume
            tailoring evidence-based instead of vibes-based. It evaluates a
            target role, selects the right positioning lane, maps source-backed
            proof points to the job&apos;s hiring thesis, runs specialized
            review agents, and renders a finalized PDF from canonical structured
            resume JSON. The system is designed to prevent unsupported claims,
            reduce overfitting to a single job description, and make the
            strongest truthful evidence obvious within a 10-second skim.
          </p>

          <div className="grid gap-8 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]">
            <div className="space-y-4">
              <h3 className="text-xs font-semibold uppercase tracking-[0.28em] text-[color:var(--color-cream)]/66">
                What the system does
              </h3>
              <ul className="grid gap-x-6 gap-y-3 sm:grid-cols-2">
                {resumeSystemCapabilities.map((capability) => (
                  <li
                    key={capability}
                    className="flex gap-2 text-sm leading-6 text-[color:var(--color-cream)]/82"
                  >
                    <span
                      aria-hidden="true"
                      className="mt-2 h-1.5 w-1.5 flex-none rounded-full bg-[color:var(--color-orange)]"
                    />
                    <span>{capability}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="space-y-4 rounded-[1.5rem] border border-white/10 bg-white/5 p-6">
              <h3 className="text-xs font-semibold uppercase tracking-[0.28em] text-[color:var(--color-cream)]/66">
                Product signals demonstrated
              </h3>
              <ul className="flex flex-wrap gap-2">
                {productSignals.map((signal) => (
                  <li
                    key={signal}
                    className="rounded-full border border-white/14 bg-white/8 px-3 py-1.5 text-xs font-medium text-[color:var(--color-cream)]/86"
                  >
                    {signal}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="flex flex-wrap gap-3 pt-2">
            <Link
              href="/products/ai-career-operating-system"
              className="inline-flex items-center justify-center gap-2 rounded-full border border-[color:var(--color-cream)] bg-[color:var(--color-cream)] px-5 py-3 text-sm font-semibold text-[color:var(--color-slate)] transition hover:bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[color:var(--color-orange)] focus-visible:ring-offset-2 focus-visible:ring-offset-[color:var(--color-slate)]"
            >
              See the product case study
              <ArrowUpRight aria-hidden="true" className="h-4 w-4" />
            </Link>
            <Link
              href="/resume/generate"
              className="inline-flex items-center justify-center gap-2 rounded-full border border-white/20 bg-transparent px-5 py-3 text-sm font-semibold text-[color:var(--color-cream)] transition hover:bg-white/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[color:var(--color-orange)] focus-visible:ring-offset-2 focus-visible:ring-offset-[color:var(--color-slate)]"
            >
              Try the live generator
            </Link>
          </div>
        </div>
      </section>

      <CTASection
        title="Need a specific version for a role?"
        description="Happy to tailor the framing once there is a concrete opportunity or recruiter brief — the system makes role-specific, source-backed versions fast."
        primaryAction={{
          href: siteConfig.linkedinUrl,
          label: "Connect on LinkedIn",
          external: true,
        }}
        secondaryAction={{
          href: siteConfig.contactHref,
          label: "Send a message",
        }}
      />
    </Container>
  );
}
